# fly.toml app configuration file generated for osu-web on 2025-04-08T23:27:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'osu-web'
primary_region = 'bom'
swap_size_mb = 512

[build]
  dockerfile = "Dockerfile"

[build.args]
  DJANGO_SETTINGS_MODULE = "backend.production"

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE = "backend.production"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="osu_web_data"
  destination="/data"
