# Generated by Django 5.2 on 2025-04-09 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import osu.player.models
import osu.team.models


class Migration(migrations.Migration):
    dependencies = [
        ("osu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.FileField(
                        blank=True, max_length=256, upload_to=osu.team.models.upload_team_logos
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True, related_name="owned_teams", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=45, null=True, unique=True)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True,
                        max_length=256,
                        null=True,
                        upload_to=osu.player.models.upload_player_profile_picture,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=5
                    ),
                ),
                ("other_gender", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "match_up",
                    models.CharField(
                        choices=[("M", "Male matching"), ("F", "Female matching")], max_length=20
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "throwing_hand",
                    models.CharField(
                        blank=True,
                        choices=[("L", "Left"), ("R", "Right")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "preffered_role",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Cutter"), ("H", "Handler")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(blank=True, related_name="players", to="osu.team"),
                ),
            ],
        ),
    ]
