# Generated by Django 5.2 on 2025-04-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("osu", "0003_matchscore_spiritscore_tournament_positionpool_pool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="base_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="sold_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
